In [1]:
# price = m1* area + m2* bedrooms + m3* age + b
# y = m1*x1 + m2*x2 + m3*m3

#Topic of this tutorial 
#Data preprocessing: Handling NA values
#Linear Regression Using Multiple Variables


In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [3]:
url = "https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/homeprices.csv"
df = pd.read_csv(url)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:

import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [5]:
#Fill any functions
# we have NaN and this is a bad thing, lets fill it with median
df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [6]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df 

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
reg = linear_model.LinearRegression()
#reg.fit(df[['area','bedrooms','age']],df.price) #train model set
#ikili [] icinde yazan independet, target ise df.price oluyor

reg.fit(df[['area','bedrooms','age']], df.price)

LinearRegression()

In [8]:
reg.coef_ 
# coefler yukarida tanimlanan m1,m2,m3

# price = m1* area + m2* bedrooms + m3* age + b

array([  112.06244194, 23388.88007794, -3231.71790863])

In [9]:
reg.intercept_
# that's b

221323.00186540437

In [10]:
# reg.fit'deki independent verileri yazalım
# area = 300, bedrooms = 3, age = 4
reg.predict([[3000,3,4]])

C:\Users\Ahmet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([614750.09629109])

In [11]:
# nasılbu sonucu bulduk
# price = m1* area + m2* bedrooms + m3* age + b
reg.coef_[0] * 3000 + reg.coef_[1] * 3 + reg.coef_[2] * 4 + reg.intercept_


614750.0962910937

In [12]:
#Exercise 

from word2number import w2n
url = "https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv"
d = pd.read_csv(url)

In [13]:
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [14]:
d.experience = d.experience.fillna("zero")
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [15]:
d.experience = d.experience.apply(w2n.word_to_num)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [16]:
import math
median_test_score = math.floor(d['test_score(out of 10)'].mean())
median_test_score

7

In [17]:
d['test_score(out of 10)'] = d['test_score(out of 10)'].fillna(median_test_score)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [18]:
reg = linear_model.LinearRegression()
#reg.fit(df[['area','bedrooms','age']], df.price)
reg.fit(d[['experience','test_score(out of 10)', 'interview_score(out of 10)']], d['salary($)'])

LinearRegression()

In [19]:
reg.predict([[2,9,6]])

C:\Users\Ahmet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [20]:
reg.predict([[12,10,10]])

C:\Users\Ahmet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])