In [1]:
import numpy as np

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [6]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [10]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [11]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

In [15]:
price_per_unit * units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [24]:
#Exercise
#url = https://github.com/codebasics/deep-learning-keras-tf-tutorial/blob/master/4_matrix_math/4_matrix_math.md
#Q1
#Below is some indian companies revenues in US dollars. 
#Using numpy can you convert this into Indian rupees? 1 USD = 75 INR

import numpy as np

revenue = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
inr = np.array([75])

In [28]:
revenue*inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [59]:
#Q2
#Below is the table showing how many flowers of each type they sold in different months
#Also given are the prices of one flower each.
#Using this find out their total sales in every month.
#

units_sold = np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit = np.array ([20,30,15])


In [60]:
np.dot(price_per_unit,units_sold)

array([1900, 2640, 1430])